### ISSUE TITLE
Question: adopt this plugin for ZenPhoto20

### ISSUE THREAD

**Issue by Jens2014** [acrylian/featured_image#4]
Hi Malte,
could you create a version which works with ZP20 too? My capabilities are not good enough to do it by myself.
Thanks for your support and best wishes,
Jens

**Comment by acrylian** [comment]
No, sorry, I only support the original Zenphoto project (for very obvious reasons).

**Comment by Jens2014** [comment]
I can understand. Thanks for your reply.
